"use client";

import { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import Breadcrumbs from "@/components/Breadcrumbs";
import { useToast } from "@/contexts/ToastContext";

interface DNSRecord {
  type: string;
  name: string;
  value: string;
  ttl?: number;
  description?: string;
}

interface Domain {
  id: string;
  domain: string;
  status: "pending" | "verified" | "failed";
  dns_records: DNSRecord[];
}

export default function DNSRecordsPage() {
  const params = useParams();
  const router = useRouter();
  const [domain, setDomain] = useState<Domain | null>(null);
  const [loading, setLoading] = useState(true);
  const [syncingToDO, setSyncingToDO] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    const token = localStorage.getItem("auth_token");
    if (!token) {
      router.push("/");
      return;
    }
    fetchDomain();
  }, [params.id, router]);

  const fetchDomain = async () => {
    try {
      const token = localStorage.getItem("auth_token");
      const res = await fetch(`/api/domains/${params.id}`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.success) {
        setDomain(data.data.domain);
      }
    } catch {
      toast("Couldn't load domain. Try again.", "error");
    } finally {
      setLoading(false);
    }
  };

  const exportToCloudflare = () => {
    if (!domain) return;
    const { domain: domainName, dns_records: records } = domain;

    const lines: string[] = [
      `; DNS Records for ${domainName}`,
      `; Generated by Freeresend`,
      `; Import this file into Cloudflare DNS`,
      ``,
    ];

    for (const record of records) {
      const name = record.name.endsWith(".")
        ? record.name
        : `${record.name}.`;
      const ttl = record.ttl || 300;

      if (record.type === "MX") {
        const idx = record.value.indexOf(" ");
        if (idx > 0) {
          const priority = record.value.substring(0, idx).trim();
          const hostname = record.value.substring(idx + 1).trim();
          lines.push(`${name}  ${ttl}  IN  MX  ${priority}  ${hostname}`);
        } else {
          lines.push(`${name}  ${ttl}  IN  MX  ${record.value}`);
        }
      } else if (record.type === "TXT") {
        const value = record.value.includes(" ")
          ? `"${record.value}"`
          : record.value;
        lines.push(`${name}  ${ttl}  IN  TXT  ${value}`);
      } else {
        lines.push(`${name}  ${ttl}  IN  ${record.type}  ${record.value}`);
      }
    }

    lines.push("");
    const blob = new Blob([lines.join("\n")], {
      type: "text/plain;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${domainName}-dns-records.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleVerifyDomain = async () => {
    if (!domain) return;
    try {
      const token = localStorage.getItem("auth_token");
      const res = await fetch(`/api/domains/${domain.id}/verify`, {
        method: "POST",
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      toast(data.message);
      fetchDomain();
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Couldn't verify domain. Wait for DNS to propagate, then try again.";
      toast(msg, "error");
    }
  };

  const handleSyncToDigitalOcean = async () => {
    if (!domain) return;
    if (
      !confirm(
        "Create these DNS records in your DigitalOcean account?"
      )
    )
      return;

    setSyncingToDO(true);
    try {
      const token = localStorage.getItem("auth_token");
      const res = await fetch(`/api/domains/${domain.id}/retry-dns`, {
        method: "POST",
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      toast(data.message);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Something went wrong";
      toast(`Couldn't sync to DigitalOcean: ${msg}`, "error");
    } finally {
      setSyncingToDO(false);
    }
  };

  if (loading) {
    return <p className="text-sm text-[#737373]">Loading DNS records...</p>;
  }

  if (!domain) {
    return <p className="text-sm text-[#a3a3a3]">Domain not found.</p>;
  }

  return (
    <div>
      <Breadcrumbs
        crumbs={[
          { label: "Domains", href: "/" },
          { label: domain.domain },
          { label: "DNS Records" },
        ]}
      />

      <div className="flex items-start justify-between mb-6">
        <div>
          <h2 className="text-lg font-semibold">
            DNS records for {domain.domain}
          </h2>
          <p className="text-sm text-[#737373] mt-1">
            Add these records to your DNS provider to verify the domain and start sending.
          </p>
        </div>
      </div>

      <div className="space-y-3">
        {domain.dns_records?.map(
          (record: DNSRecord, index: number) => (
            <div
              key={index}
              className="bg-[#fafafa] border border-[#e5e5e5] rounded-lg p-4"
            >
              <div className="grid grid-cols-3 gap-4 text-sm">
                <div>
                  <span className="text-xs text-[#737373]">Type</span>
                  <div className="mt-0.5 font-mono">{record.type}</div>
                </div>
                <div>
                  <span className="text-xs text-[#737373]">Name</span>
                  <div className="mt-0.5 font-mono break-all">
                    {record.name}
                  </div>
                </div>
                <div>
                  <span className="text-xs text-[#737373]">Value</span>
                  <div className="mt-0.5 font-mono text-xs bg-white border border-[#e5e5e5] rounded p-2 break-all">
                    {record.value}
                  </div>
                </div>
              </div>
              {record.description && (
                <p className="mt-2 text-xs text-[#a3a3a3]">
                  {record.description}
                </p>
              )}
            </div>
          )
        )}
      </div>

      <div className="mt-6 flex gap-3">
        <button
          onClick={() => router.back()}
          className="rounded-lg border border-[#e5e5e5] px-4 py-2 text-sm text-[#525252] hover:text-[#171717] transition-colors"
        >
          Back
        </button>
        <button
          onClick={exportToCloudflare}
          className="rounded-lg bg-[#171717] px-4 py-2 text-sm text-white hover:bg-[#404040] transition-colors"
        >
          Export to Cloudflare
        </button>
        <button
          onClick={handleSyncToDigitalOcean}
          disabled={syncingToDO}
          className="rounded-lg bg-[#171717] px-4 py-2 text-sm text-white hover:bg-[#404040] transition-colors disabled:opacity-50"
        >
          {syncingToDO ? "Syncing..." : "Sync to DigitalOcean"}
        </button>
        <button
          onClick={handleVerifyDomain}
          className="rounded-lg bg-[#171717] px-4 py-2 text-sm text-white hover:bg-[#404040] transition-colors"
        >
          Check verification
        </button>
      </div>
    </div>
  );
}
